spring:
  datasource:
    username: ${USERNAME}
    password: ${PASS}
    url: jdbc:postgresql://localhost:5432/skillbox_team13
  liquibase:
    enabled: true
    change-log: db/db.yml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  token:
    secret: stream-team13
    ordinary:
      expired: 3600000
    recovery:
      expired: 60000
    mail:
      expired: 60000

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL}
  password: ${EMAILPASS}
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true

server:
  port: ${PORT:8080}

server.base_url: https://team13.herokuapp.com
