spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/skillbox_team13
  liquibase:
    enabled: true
    change-log: db/db.yml
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none