spring:
  datasource:
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:skillbox_team13}
  liquibase:
    enabled: true
    change-log: db/db.yml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  token:
    secret: stream-team13
    ordinary:
      expired: 3600000
    recovery:
      expired: 60000
    mail:
      expired: 60000

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL}
  password: ${EMAILPASS}
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true

server:
  port: ${PORT:8080}

server.base_url: ${BASE_URL:https://team13.herokuapp.com}

logging:
  level:
    liquibase: INFO
    org:
      springframework: INFO
      hibernate: INFO
    ru:
      skillbox: DEBUG
  pattern:
    console: "%date{dd.MM-HH:mm:ss.SSS} %highlight(%5level) [%thread] %logger{45}: %message %n"
